name = "CryptoAPIs"
uuid = "5e3d4798-c815-4641-85e1-deed530626d3"
version = "0.16.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSONWebTokens = "9b8beb19-0777-58c6-920b-28f749fee4d3"
NanoDates = "46f1a544-deae-4307-8689-c12aa3c955c6"
Nettle = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"
Serde = "db9b398d-9517-45f8-9a95-92af99003e0e"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
EasyCurl = "5dc68c43-2cae-45c1-9c9f-30d6e2b9e002"

[compat]
JSONWebTokens = "1.1.1"
NanoDates = "0.3.0"
Nettle = "1.0.0"
TimeZones = "1.13.0"
Serde = "3.0.0"
EasyCurl = "2.0.0"
julia = "1.8"
